
name: build

on:
  push:
    branches:
      - master
      - pipeline

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      # Our build script needs access to all previous tags, so we add fetch-depth: 0
      with:
        fetch-depth: 0
    
    - name: Setup PHP, with composer and extensions
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, mysql, pdo_mysql
    
    - name: Install dependencies
      run: composer install

    - name: Build
      uses: thedoctor0/zip-release@master
      with:
        filename: 'mto-woocommerce.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'

    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
          artifacts: "mto-woocommerce.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true