name: Test and Build mto-woocommerce

on:
  push:
    branches:
      - master
      - 'feature/*'
      - 'bugfix/*'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
        matrix:
          php-versions: ['7.3', '7.4']

    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate --strict
      
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
      
      - name: Install dependencies
        run: composer install --ignore-platform-reqs --prefer-dist --no-progress --no-suggest

      # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
      # Docs: https://getcomposer.org/doc/articles/scripts.md

      # - name: Run test suite
      #   run: composer run-script test

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
  
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-
    
      - name: Install dependencies
        run: composer install --ignore-platform-reqs --prefer-dist --no-progress --no-suggest

      # TODO: Rename artifact to use git tag name
      - name: Build
        uses: thedoctor0/zip-release@master
        with:
          filename: "mto-woocommerce-${{ github.sha }}.zip"
          exclusions: '*.git* /*node_modules/* .editorconfig'

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          path: "mto-woocommerce-${{ github.sha }}.zip"

      - name: Create release
        uses: ncipollo/release-action@v1
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        with:
          name: "mto-woocommerce-${{ github.sha }}"
          artifacts: "mto-woocommerce-${{ github.sha }}.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: true